### ISSUE TITLE
Join forces with Ant Design of React?

### ISSUE THREAD

**Issue by kvetoslavnovak** [uxcore/uxcore#1]
Hi, excelent job. 
Do you know about Ant Design of React project?  UXCore seems to compete with their project, 
http://ant.design/docs/react/introduce
https://github.com/ant-design/ant-design

It would be great if you can join your forces and work together. Combination of AntD and UXCore would be great.

**Comment by eternalsky** [comment]
Thanks for your attention and appreciation. AntD and UXCore  are both built based on the same fundamental [react components](react-component)，which we work together to make better. Our difference is mainly about design and project solutions, which comes from different business background.
