### ISSUE TITLE
uxcore-select2 value div text-overflow is not set.

### ISSUE THREAD

**Issue by yukap6** [uxcore/uxcore#13]
class like .kuma-select2-selection-selected-value should add style as follows E.G:
{
    right: 20px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}

**Comment by eternalsky** [comment]
fix in  https://github.com/uxcore/uxcore-select2/commit/1068f5683c8f352a39d85100c703a53e8de2d717
