### ISSUE TITLE
Uncaught ReferenceError: React is not defined in meteor project

### ISSUE THREAD

**Issue by Stupra-GZ** [uxcore/uxcore#2]
I use in Meteor.js project，installed by npm，npm version is 3.9.6，the developer tools will show Uncaught ReferenceError: React is not defined in meteor project when I import uxcore

ReferenceError: React is not defined
__WEBPACK_AMD_DEFINE_ARRAY__	@	modules.js?hash=637c031…:19853
__webpack_require__	@	modules.js?hash=637c031…:788
Object.create.constructor.value	@	modules.js?hash=637c031…:19715
__webpack_require__	@	modules.js?hash=637c031…:788
_typeof	@	modules.js?hash=637c031…:16004
__webpack_require__	@	modules.js?hash=637c031…:788
(anonymous function)	@	modules.js?hash=637c031…:850
__webpack_require__	@	modules.js?hash=637c031…:788
(anonymous function)	@	modules.js?hash=637c031…:808
(anonymous function)	@	modules.js?hash=637c031…:811
webpackUniversalModuleDefinition	@	modules.js?hash=637c031…:761
meteorInstall.node_modules.uxcore.lib.uxcore.js	@	modules.js?hash=637c031…:768
fileEvaluate	@	install.js:153
require	@	install.js:82
Mp.import	@	runtime.js:70
meteorInstall.client.modules.login.index.js	@	app.js?hash=3ec6cd4…:1564
fileEvaluate	@	install.js:153
require	@	install.js:82
Mp.import	@	runtime.js:70
meteorInstall.client.modules.core.routes.js	@	app.js?hash=3ec6cd4…:1345
fileEvaluate	@	install.js:153
require	@	install.js:82
Mp.import	@	runtime.js:70
meteorInstall.client.modules.core.index.js	@	index.js:1
fileEvaluate	@	install.js:153
require	@	install.js:82
(anonymous function)	@	app.js?hash=3ec6cd4…:1991

**Comment by eternalsky** [comment]
Can you tell me the way you import uxcore ?

**Comment by kvetoslavnovak** [comment]
Quite similar error here. Meteor starts OK, but in the console here:
`Uncaught ReferenceError: React is not defined    modules.js?hash=36eb669…:19804`

In Meteor app I installed React `meteor npm install --save react react-dom` and UXCore `meteor npm install --save uxcore` . Meteor app files import everything just ok, when I use AntDesign instead of UXCore in this app everything runs without issues,

**Comment by Stupra-GZ** [comment]
I import the React and uxcore
```
import React from 'react';
import { Form, Button } from 'uxcore';
```
I also try import React Dom, also not work
`import ReactDOM from 'react-dom';`

**Comment by Stupra-GZ** [comment]
If I only install uxcore-button, Meteor app files import the button just ok

**Comment by eternalsky** [comment]
@Stupra-GZ yes, uxcore full package will change require('react') to window.React，so you need import react & react-dom script in your app html file. but your suggestion is right, we can maintain require('react')  if it is commonJS mode.

**Comment by eternalsky** [comment]
@Stupra-GZ @kvetoslavnovak we have just released a [new version](https://github.com/uxcore/uxcore/releases/tag/0.2.3) to fix this issue. Please try it.

**Comment by Stupra-GZ** [comment]
@eternalsky Good，everything just ok now.

**Comment by kvetoslavnovak** [comment]
It works now. Thank you. great work!!!
