### ISSUE TITLE
how to use custom theme with less

### ISSUE THREAD

**Issue by isoloist** [uxcore/uxcore#21]
import my-theme.less in entry.jsx can't work

**Comment by eternalsky** [comment]
1. where does my-theme.less come from?
2. the way in which you import my-theme.less is unknown.

Could you please support more information about your problem?

**Comment by isoloist** [comment]
my-theme.less like this
@base-font: tahoma, arial, 'PingFang SC', 'Hiragino Sans GB', 'WenQuanYi Micro Hei', 'Microsoft YaHei', 'SimSun', sans-serif
@brand-primary: #996699
@brand-secondary: #2c2f33
@brand-complement: #00b3e8
@brand-comosite: #00c587
@brand-deep: #996699
@brand-danger: #f04631
@brand-warning: #f5a12a
@brand-success: #66bd5c
@brand-info: #45a8e6
@brand-query: #24bee8
@gray-dark: #333
@gray: #666
@gray-light: #999
@gray-lighter: #ccc
@link-color: #3B8FD9
@link-hover-color: #1A78B8
@link-active-color: #1A78B8
@link-visited-color: #73461d
@link-disabled-color: #ccc

@import 

add
   import '../../css/my-theme.less'
at the head of  entry.jsx

**Comment by eternalsky** [comment]
Do you have some error message in your console?
