### ISSUE TITLE
import component as required文档缺少svg-path相关

### ISSUE THREAD

**Issue by yidazh** [uxcore/uxcore#22]
> import component as required
> Install the component

> npm install uxcore-button kuma-base
> import Button from 'uxcore-button';
> And import style in your less file

> @import '~kuma-base/theme/blue.less'; // or orange.less global variables which components need
> @import '~kuma-base/core.less'; // base element style and reset
> @import '~uxcore-button/src/Button.less';

以上是官网指引文档，按照这样配，webpack提示svg模块找不到。用真实路径覆盖svg-path变量即可解决
``` less
@svg-path: '~kuma-base/core/svg/blue/';
```

**Comment by eternalsky** [comment]
fixed, 3ks
