### ISSUE TITLE
form 里面的InputFormField等组件宽度怎么修改？ 

### ISSUE THREAD

**Issue by weinengjian** [uxcore/uxcore#23]
form 里面的InputFormField等组件宽度怎么修改？

**Comment by eternalsky** [comment]
可以通过调节每个 field 的 jsxflex 来调节。

**Comment by weinengjian** [comment]
我是想要一行里面只有一个input  而且只占一半的宽度

**Comment by weinengjian** [comment]
jsxflex也不行的   关键是自己写的样式无效  这个太麻烦了    大佬  求助啊

**Comment by weinengjian** [comment]
自定义样式里面 !important 可以了

**Comment by eternalsky** [comment]
@weinengjian 你的 case 可以用 OtherFormField 去做去占位，尽量不要用 !important
