### ISSUE TITLE
SelectFormField的text值怎么获取啊？ 

### ISSUE THREAD

**Issue by weinengjian** [uxcore/uxcore#24]
{value:1, text: '测试值'}       现在只能获得value值，  没有方法可以获得text

**Comment by eternalsky** [comment]
1. text 可以通过传入数据自己再找回来。
2. 可以使用 labelInValue 的模式，不过值的传递会有所变化。从单纯的 value，变成 {key: xxx, label: xxx}，label 就是 text

**Comment by weinengjian** [comment]
谢谢啊   你们维护的很好  多谢

**Comment by weinengjian** [comment]
我的不支持这种结构的  可能是因为版本太低了

**Comment by eternalsky** [comment]
这个在很早之前已经支持了，你现在是什么版本的 uxcore？

**Comment by weinengjian** [comment]
看不出来  可能是2.0  2点几的

**Comment by eternalsky** [comment]
uxcore 整包的版本只到 0.15.x，你这个版本有点看不太懂~ 推荐用 整包下的使用方法哈

**Comment by weinengjian** [comment]
麻烦你了    本来想偷懒的  现在还是要再按id匹配下  版本也是不能改的 只能这样了
