### ISSUE TITLE
TreeSelect 我的样式和文档差很多

### ISSUE THREAD

**Issue by weinengjian** [uxcore/uxcore#25]
https://static.dingtalk.com/media/lALPACOG83D8GabMzs0BTw_335_206.png_620x10000q90g.jpg?auth_bizType=IM&auth_bizEntity=%7B%22cid%22%3A%2276122802%3A83687306%22%2C%22msgId%22%3A%2231528012930%22%7D&open_id=76122802
https://static.dingtalk.com/media/lALPACOG83D8z_ZNzII_130_77.png_620x10000q90g.jpg?auth_bizType=IM&auth_bizEntity=%7B%22cid%22%3A%2276122802%3A83687306%22%2C%22msgId%22%3A%2230862888172%22%7D&open_id=76122802

**Comment by weinengjian** [comment]
有人遇到这样吗

**Comment by eternalsky** [comment]
版本的问题，请使用最新版本。
