### ISSUE TITLE
IE9,10兼容问题

### ISSUE THREAD

**Issue by FMMLMF** [uxcore/uxcore#27]
报错：
SCRIPT438:对象不支持“listen”属性或方法

**Comment by eternalsky** [comment]
请说明一下使用的版本、使用了哪些组件，是否有做 es5-shim 处理

**Comment by eternalsky** [comment]
另外请给出是组件 js 导致报错的截图或说明

**Comment by FMMLMF** [comment]
使用nowa快速构建的项目
nowa init https://github.com/nowa-webpack/template-uxcore/archive/v2.zip
报错的地方是引入的js：
  <script src="//g.alicdn.com/platform/c/??jquery/1.11.3/dist/jquery.min.js,lodash/3.10.1/lodash.min.js,react/0.14.2/react-with-addons.min.js,react/0.14.2/react-dom.min.js,lie/3.0.2/dist/lie.polyfill.min.js,react-router/2.8.1/umd/ReactRouter.js,reflux/0.5.1/dist/reflux.min.js,natty-storage/1.1.1/dist/natty-storage.min.js,natty-fetch/2.2.0/dist/natty-fetch.pc.min.js"></script>

**Comment by eternalsky** [comment]
去掉 reflux 的 min 看一下

**Comment by FMMLMF** [comment]
去了都获取不到js了啊

**Comment by eternalsky** [comment]
实测：http://g.alicdn.com/platform/c/??jquery/1.11.3/dist/jquery.min.js,lodash/3.10.1/lodash.min.js,react/0.14.2/react-with-addons.min.js,react/0.14.2/react-dom.min.js,lie/3.0.2/dist/lie.polyfill.min.js,react-router/2.8.1/umd/ReactRouter.js,reflux/0.5.1/dist/reflux.js,natty-storage/1.1.1/dist/natty-storage.min.js,natty-fetch/2.2.0/dist/natty-fetch.pc.min.js

这个文件是有的，不知道你是怎么去的

**Comment by FMMLMF** [comment]
搞错了，但是还是报同样的错

**Comment by eternalsky** [comment]
通过目前的报错信息无法定位你的问题，可以提供更详细的说明吗？比如是否使用了其他的什么库，因为我们很多项目都是兼容到 IE9的，并没有出现你说的问题。

**Comment by FMMLMF** [comment]
项目中加了一个单独的登录页面，有用到query， 版本v1.11.1
还有一个base64加密，git地址：https://github.com/dankogai/js-base64

**Comment by FMMLMF** [comment]
jquery

**Comment by eternalsky** [comment]
能否在 IE10 下断一下点，看下具体是哪里的 Listen 不存在，然后我们再看。

**Comment by FMMLMF** [comment]
![1111111](https://user-images.githubusercontent.com/8913786/29962874-56f190a4-8f37-11e7-92bd-9d787a3e5548.jpg)

**Comment by eternalsky** [comment]
这是 reflux 里的代码，请去看下 reflux 相关的兼容性问题，并且对应版本引入对应的 shim 脚本

**Comment by eternalsky** [comment]
https://github.com/reflux/refluxjs/issues/485
