### ISSUE TITLE
请问下select2是不是只能按key值查询

### ISSUE THREAD

**Issue by weinengjian** [uxcore/uxcore#28]
按option里面的文本查询  数据绑定不到下拉组件里面去  只能按key值查询时是正常的

**Comment by eternalsky** [comment]
描述的不是很清晰，能详细描述下你要做的事情吗

**Comment by weinengjian** [comment]
<select2><option key='test'>测试文本</option></select2>   就是一个实现模糊查询的需要  你输入‘测试’后台返回的数据不能渲染在option中，  输入‘test’ key值却是可以的    现在只好把文本值也放到key里面的

**Comment by weinengjian** [comment]
`<select2><option key = 'test'>测试文本</option></select2>`

**Comment by eternalsky** [comment]
看下文档里和 filter 相关的配置项。

**Comment by eternalsky** [comment]
reopen it if necessary
