### ISSUE TITLE
SearchFormField 的not found可以去掉吗 

### ISSUE THREAD

**Issue by weinengjian** [uxcore/uxcore#29]
SearchFormField  只是想把它作为一个输入框  不用编辑搜索功能

**Comment by eternalsky** [comment]
问题和描述的需求好像不太一样，如果 notFound 不需要的话，可以配置 notFoundContent 为自己想要的没有数据时的文案，如果是指向要一个输入框的话，可以直接使用样式，`<Input className="kuma-input" />`
