### ISSUE TITLE
treeSelect组如何可以获得选中节点的父组件吗

### ISSUE THREAD

**Issue by weinengjian** [uxcore/uxcore#30]
treeSelect使用在Form.createFormField中，  获得form的values,或者onselect只能获得选中节点的value.

**Comment by eternalsky** [comment]
treeSelect onChange 可以拿到当前的 value，label 和 node 节点，一般父级建立关联来拿到。

**Comment by weinengjian** [comment]
我再试试吧   但是onChange现在不触发 因为组件是在createFormField里封装的
