### ISSUE TITLE
ref设置字符串和回调的问题

### ISSUE THREAD

**Issue by IVLIU** [uxcore/uxcore#32]
设置字符串ref可以每次都获取到组件实例，但是设置回调ref第二次传入（也可能是第一次）参数会变成null，导致出现错误，比如getValues（）是undefined错误

**Comment by eternalsky** [comment]
ref 的问题通常都是 React 生命周期使用不当造成的，可以贴下你的 code，来分析一下。

**Comment by eternalsky** [comment]
@IVLIU 还有后续的反馈吗~

**Comment by eternalsky** [comment]
reopoen it if neccessary
