### ISSUE TITLE
uxcore ref设置问题

### ISSUE THREAD

**Issue by IVLIU** [uxcore/uxcore#33]
设置字符串ref可以每次都获取到组件实例，但是设置回调ref第二次传入（也可能是第一次）参数会变成null，导致出现错误，比如getValues（）是undefined错误
`<Form ref="form" className="demo-basic-form">
                    <Input jsxname="theme" jsxlabel="主题"  jsxplaceholder="请输入主题"/>
                    <Input jsxname="location" jsxlabel="地点"  jsxplaceholder="请输入地点"/>
                    <Date jsxname="date" jsxlabel="时间" jsxtype="cascade" autoMatchWidth />
                    <TextArea jsxname="content" jsxlabel="内容" />
                    <Other>
                        <Button style={{ marginLeft: '88px' }} onClick={me.handleSubmit.bind(me)}>确定</Button>
                    </Other>
                </Form>`
这个是uxcore Form例子的第一个的代码，单击button功能正常
`<Form 
                    ref={(c) => {this.form = c;}} 
                    className="demo-basic-form" 
                    jsxvalues={this.state.values} 
                    jsxonChange={(values) => {this.handleChange(values)}}
                    size={this.state.values.size}
                >
                    <Select jsxname="size" jsxlabel="尺寸"  jsxdata={[
                        {value: 'large', text: '大'},
                        {value: 'middle', text: '中'},
                        {value: 'small', text: '小'},
                    ]}/>
                    <Input jsxname="location" jsxlabel="地点"  jsxplaceholder="请输入地点"/>
                    <Date jsxname="date" jsxlabel="时间" jsxtype="cascade" autoMatchWidth />
                    <TextArea jsxname="content" jsxlabel="内容" />
                    <Other>
                        <Button style={{ marginLeft: '88px' }} onClick={me.handleSubmit.bind(me)}>确定</Button>
                    </Other>
                </Form>`
这是第二个例子，单击button控制台报错

**Comment by eternalsky** [comment]
请一个问题不要开多个讨论。
