### ISSUE TITLE
在uxcore中未找到Tinymce(富文本)这个组件

### ISSUE THREAD

**Issue by cxiaoyan** [uxcore/uxcore#34]
1、我直接用tnpm install uxcore --save 安装的uxcore。但是在uxcore的lib库中没有找到Tinymce。所以引用就找不到了。
2、因为uxcore中找不到Tinymce（富文本）这个组件，我单独安装了uxcore-tinymce（tnpm install uxcore-tinymce --save)这样子的话引用的过程中会报错。报错内容如下：
![image](https://user-images.githubusercontent.com/22631010/32761562-05d39f6e-c92f-11e7-9e38-eb68b87569f1.png)

**Comment by eternalsky** [comment]
这是因为你没有引用 tinymce.js ，UXCore 的 Tinymce 只是 tinymce 的一个 React 容器。如果你是用 nowa 脚手架生成的，html 里面有对应的注释。

**Comment by cxiaoyan** [comment]
好的，谢谢
