### ISSUE TITLE
Carousel刷新后不能切换

### ISSUE THREAD

**Issue by panjiefeng** [uxcore/uxcore#39]
Carousel组件创建后能够切换，当数据改变Carousel组件刷新后就不再进行切换。
环境：
1. 使用的是nowa进行创建的项目，项目中安装的"uxcore": "^0.15.18"
2. 使用codeOpen创建的例子，模拟组件刷新，在浏览器中**依然能够进行切换**（codeOpen无法重现）。我将浏览器只能够使用到的uxcore的版本（https://g.alicdn.com/uxcore/uxcore/0.1.17/uxcore.min.js）替换到本地仍然不能切换。

想不出还有其他什么原因了
无法重现的codeOpen的地址：https://codepen.io/panjunfen/pen/bLxeEw?editors=0010

**Comment by eternalsky** [comment]
无法复现的问题，我这里也无法处理，先关闭，有能复现的方法再 reopen。
