### ISSUE TITLE
Button: size 中间大小的英文标识 medium 和其他组件中间大小的英文标识不相同

### ISSUE THREAD

**Issue by caiyongmin** [uxcore/uxcore#40]
### Button
中间大小英文标识：medium。
![image](https://user-images.githubusercontent.com/11053605/36968625-09af2f42-209e-11e8-83c3-a91d4686e95f.png)

### Select2
中间大小英文标识：middle。
![image](https://user-images.githubusercontent.com/11053605/36968578-e127dc7c-209d-11e8-9e93-e2e0423cef10.png)

### CascadeSelect
中间大小英文标识：middle。
![image](https://user-images.githubusercontent.com/11053605/36968593-f38667d0-209d-11e8-9ea3-fc62b4f1a6d8.png)

后期是否考虑统一？

**Comment by eternalsky** [comment]
恩，考虑统一成 middle，同时兼容 medium

**Comment by eternalsky** [comment]
已完成：https://github.com/uxcore/uxcore-button/commit/cf4f690aeca3170be9a84c87fed0e1bab5d527ae，待周四统一发包

**Comment by eternalsky** [comment]
已经发布。
