### ISSUE TITLE
CascadeSelect: 中间大小的高度和其他选择器的高度不一致

### ISSUE THREAD

**Issue by caiyongmin** [uxcore/uxcore#41]
见下图，级联选框的高度比下拉选择框的高度，高两个像素，size 都为 middle。

![image](https://user-images.githubusercontent.com/11053605/37151058-0284c574-230f-11e8-9d2e-9b483ff7fa9e.png)

**Comment by lpgray** [comment]
OK，马上修改！

**Comment by lpgray** [comment]
1070637daa8f07c7a2d36cfec3268b091eb8ec62
已经修复这个问题

**Comment by eternalsky** [comment]
带周四统一发包。

**Comment by eternalsky** [comment]
已经发布。
