### ISSUE TITLE
Calendar 的国际化有问题

### ISSUE THREAD

**Issue by fengsx** [uxcore/uxcore#42]
0.16.3 的时候还是好的，从 0.17.0 开始出问题。

### 0.16.3
![image](https://user-images.githubusercontent.com/7709602/36972023-945d257c-20a8-11e8-9ccb-3753739f8beb.png)

### 0.17.0
![image](https://user-images.githubusercontent.com/7709602/36972160-13392a12-20a9-11e8-8aaf-dfb29fbef2aa.png)

同时输入框中的 placeholder 也没有国际化

**Comment by eternalsky** [comment]
已修复，待周四统一发包。https://github.com/uxcore/uxcore-calendar/commit/00c3252b3de167eda172156d7d866151fd833a21
