### ISSUE TITLE
pagination 组件 是否可以考虑支持增加一个每页显示多少条组件

### ISSUE THREAD

**Issue by swz19920821** [uxcore/uxcore#44]
pagination 组件 是否可以考虑支持增加一个每页显示多少条组件，可以选择每页显示多少条的那种，现在我们使用的时下拉单选来实现的

**Comment by eternalsky** [comment]
这个是支持的，showSizeChanger

**Comment by eternalsky** [comment]
还有很多可以展示的，可以看下文档。
