### ISSUE TITLE
上传组件可以实现压缩图片吗？

### ISSUE THREAD

**Issue by JaonDong** [uxcore/uxcore#45]
上传组件可以实现压缩图片吗？ 或者我们能在哪里嫁接压缩？谢谢

**Comment by yanbingbing** [comment]
通过 切片 事件(onfileuploadpreparing)可以改变一些东西，你拿到原来的文件blob，用一些开源压缩方案，压缩后，返回新的blob，设置进去就OK了，

**Comment by JaonDong** [comment]
@yanbingbing 这个方式我试了，但是不行，上传后的大小并没有改变，但Blob的大小是被压缩了

**Comment by JaonDong** [comment]
@yanbingbing 可能是压缩方法是图片load后的，即压缩方法是异步的。

**Comment by yanbingbing** [comment]
嗯，你要return 一个 promise

**Comment by yanbingbing** [comment]
@JaonDong 你要return一个promise
