### ISSUE TITLE
textarea-form-field autosize

### ISSUE THREAD

**Issue by LouieXie** [uxcore/uxcore#5]
初次显示form表单时，如果TextAreaFormField的内容过长，TextAreaFormField并不会自动将内容撑开，需要在输入框中敲击回车才回将内容撑开

**Comment by eternalsky** [comment]
新版已经修复此问题，若还有类似问题，请 reopen 这个 issue

**Comment by eternalsky** [comment]
fix in https://github.com/uxcore/uxcore-textarea-form-field/commit/3ec7396c56cabd37ce16db1ac5e11558cfcec25b
