### ISSUE TITLE
Mention functionality within Tinymce?

### ISSUE THREAD

**Issue by kvetoslavnovak** [uxcore/uxcore#7]
Hello, is it possible to use Mention functionality within Tinymce component? I am not able to get it work. It would be great feature. 
Thank you very much.

**Comment by eternalsky** [comment]
It's in our plan, but not high priority. Maybe you can develop a plugin for tinymce at preset.

**Comment by macisi** [comment]
I will add this feature in [uxcore-mention@0.3.0](https://github.com/uxcore/uxcore-mention/tree/v0.3.0) 😊

**Comment by macisi** [comment]
done.
please use uxcore-mention@0.3.1
