### ISSUE TITLE
Cannot find module 'util'

### ISSUE THREAD

**Issue by SvenWangChina** [uxcore/uxcore#8]
I installed uxcore-form use `npm install uxcore-form`, I use `import Form from 'uxcore-form'` import it, the console will show following error:
```
Uncaught Error: Cannot find module 'util'
require @ install.js:85
(anonymous function) @ YearCalendar.js:33
isNode @ YearCalendar.js:20
meteorInstall.node_modules.deepcopy.deepcopy.js @ YearCalendar.js:24
fileEvaluate @ install.js:153
require @ install.js:82
meteorInstall.node_modules.uxcore-form.build.Form.js @ PopupInner.js:35
fileEvaluate @ install.js:153
require @ install.js:82
meteorInstall.node_modules.uxcore-form.build.index.js @ Popup.js:10
fileEvaluate @ install.js:153
require @ install.js:82
Mp.import @ runtime.js:70
meteorInstall.client.modules.admin.components.SignIn.index.js @ app.js?hash=29bc961…:1304
fileEvaluate @ install.js:153
require @ install.js:82
(anonymous function) @ app.js?hash=29bc961…:3786
```

I use uxcore-button is ok.

**Comment by eternalsky** [comment]
I think maybe `uxcore-form` is not installed completely in your project. try to uninstall and reinstall it.

**Comment by SvenWangChina** [comment]
It don't work when I try to uninstall and reinstall it. It installed completely. I install it in my Meteor.js project, the Node.js version is 0.10.46, the Npm version is 3.10.5

**Comment by eternalsky** [comment]
cannot reproduce this problem, need more info, Could you please help us debug it and provide more info about what file is missing. From the info above, it seems the util module depended by YearCalendar, however this file exists in fact.

**Comment by SvenWangChina** [comment]
I fixed it, it need install two packages `meteor npm install --save meteor-node-stubs indexof`. I don't know why it need them.
