### ISSUE TITLE
how to import a single component from uxcore

### ISSUE THREAD

**Issue by SvenWangChina** [uxcore/uxcore#9]
I install the uxcore, but how to import a single component from uxcore? 
I don't want to use `import { Button } from 'uxcore'`. It will import the whole uxcore.
Use `import Button from 'uxcore-button'` is ok, but I will install multiple components.
Have any way like `import Button from 'uxcore/lib/Button'`.

**Comment by eternalsky** [comment]
It's a good suggest. We will support it in maybe next version or 0.4.x version.

**Comment by eternalsky** [comment]
fix in ver. 0.3.1

**Comment by SvenWangChina** [comment]
0.3.1 don't release... I can't update.
